* Logic

** Logic and bar graphs                                              :theory:
#+ATTR_BEAMER: :overlay <+->

For each student $\omega$, we define:
- $m(\omega)$: the student is male
- $f(\omega)$: the student is female
- $s(\omega)$: the student is in the faculty of science
- $l(\omega)$: the student is in the faculty of law
- $e(\omega)$: the student is in the faculty of economics

Clearly, if $s(\omega)$ is true then $l(\omega), e(\omega)$ are false.

Let us now associate these statements with sets, e.g.
\[
S = \{\omega : s(\omega) = 1\}
\]
being the set of students which are in the faculty of science. Clearly:
\[
s(\omega) = 1 \Leftrightarrow \omega \in S.
\]

** Logic and sets :theory:
#+ATTR_BEAMER: :overlay <+->
We can associate events with sets in a universe. The following laws apply:

1. There is a universe $\Omega$ of possible outcomes
2. Consider an individual outcome $\omega \in \Omega$:
(a) If $\omega \in A$ ,then we say that *$A$ is true*.
(b) If $\omega \notin A$ ,then we say that *$A$ is false*.
3. Let $\neg A$, read 'not A', be the complement $\Omega \setminus A$:
   If $A$ is true, then $\neg A$ is false and vice-versa.
4. $B$ is a subset of A (i.e. $B \subset A$) iff $B$ *implies* $A$.
5. If $A$ and $B$ are disjoint, i.e. $A \cap B = \emptyset$ (they have
   an empty inersection) then $A, B$ are *mutually exclusive*. That
   means that it is impossible for $A, B$ to both be true.


* Bayesian
  
** Bayesian analysis                                     :theory:probability:
#+ATTR_BEAMER: :overlay <+->
- Recall the definition of Conditional probability:
 \[
 P(A | B) = P(A \cap B) / P(B)
 \]
 i.e. the probability of A happening if B happens.
- It is also true that:
 \[
 P(B | A) = P(A \cap B) / P(A)
 \]
- Combining the two equations, reverse the conditioning:
 \[
 P(A | B) = P(B | A) P (A) / P(B)
 \]

- So we can reverse the order of conditioning, i.e. relate to the probability of A given B to that of B given A.


** The murder problem

   Somebody saw somebody matching their description and he was found
   in the neighbourghood. There is no other evidence.

   There are two possibilities:
   - $H_0$: They are innocent.
   - $H_1$: They are guilty.

   What is your belief that they have committed the crime? 

** Prior elicitation

   Let's elicit the belief by voting: How many think they are guilty,
   divided by the number of people in class.

   Let us call this $P(H_1)$. This is a purely subjective measure!

** DNA test

*** DNA test properties
#+ATTR_BEAMER: :overlay <+->
- $D$: Test is positive
- $P(D | H_0) = 10\%$: False positive rate
- $P(D | H_1) = 100\%$: True positive rate

*** Run the test
#+ATTR_BEAMER: :overlay <+->
- The result is either positive or negative ($\neg D)$.
- What is your belief *now* that the suspect is guilty?

** Everybody is a suspect

- Run a DNA test on everybody.
- What is different from before?
- Who has a positive test?
- What is your belief that the people with the positive test are guilty?

** Explanation
   #+ATTR_BEAMER: :overlay <+->
- Let $D$ denote a positive test and $\neg D$ a negative one. 
- False positive rate: $P(D | H_0) = 0.1$
- Probability of innocence: $P(H_0 | D) = P(D \cap H_0) / P(D) = P(D | H_0) P(H_0) / P(D)$
- Marginal probability: $P(D) = P(D | H_0) P(H_0) + P(D | H_1) P(H_1)$
- Bayes's theorem: P(H_0 | D) = \frac{P(D | H_0) P(H_0)}{P(D | H_0) P(H_0) + P(D | H_1) P(H_1)}
- Assuming $P(D | H_1) = 1$, and setting $P(H_0) = q$, this gives
   \[
   P(H_0 | D) = \frac{0.1 q}{0.1 q + 1 - q} =  \frac{q}{10 - 9q}
   \]





